### ISSUE TITLE
Rebuild coordinate system may fail for `PrimitiveInternalCoordinates`

### ISSUE THREAD

**Issue by jsjyhzy** [leeping/geomeTRIC#160]
When optimizing with `coordsys="prim"`, it will occasionally raise the error `'PrimitiveInternalCoordinates' object has no attribute 'conmethod'` from the following line

https://github.com/leeping/geomeTRIC/blob/9981b39fa83b6e4cc0e369a05d615235cc639458/geometric/optimize.py#L219

And it seems, in `prim`, the `conmethod` was never be used

https://github.com/leeping/geomeTRIC/blob/9981b39fa83b6e4cc0e369a05d615235cc639458/geometric/internal.py#L2005-L2024

in which case the creation of `PrimitiveInternalCoordinates` at first time would be fine, while re-creation of it fails.

I wonder if it is the problem in `optmize.py` which could be fixed easily, or the so called `conmethod` is simply not implemented for `PrimitiveInternalCoordinates` yet?

**Comment by leeping** [comment]
Thanks for the issue report, you are correct that this line contains a mistake:

https://github.com/leeping/geomeTRIC/blob/9981b39fa83b6e4cc0e369a05d615235cc639458/geometric/optimize.py#L219

The context is that 
1) `coordsys="prim"` is mainly implemented for reference in geomeTRIC and is not as high-performing as other options such as `coordsys="tric"` or `coordsys="dlc"`.  Therefore it is recommended that you use the default coordinate system or one of the two latter options.

2) The `conmethod` keyword refers to the algorithm for constrained optimization, and constrained optimizations are only possible when using `coordsys="tric"` or `coordsys="dlc"`.  The `conmethod` attribute does not exist in the other coordinate systems.  Therefore, line 219 of optimize.py is a bug that causes errors only when using coordinate systems other than `"tric"` or `"dlc"`.  I missed this bug because I seldom use any coordinate system other than those two.

To fix the bug, you should be able to change the code to something like this:

```
IC1 = self.IC.__class__(newmol, connect=self.IC.connect, addcart=self.IC.addcart, build=False, conmethod=self.IC.conmethod if hasattr(self.IC, 'conmethod') else 0) 
```

It will first check to see if the `conmethod` attribute exists before using its value.  If the attribute does not exist then it will use zero and the `PrimitiveInternalCoordinates` class should ignore it.  You can submit a PR with this fix or I can fix it myself when I have a free moment.

Thanks,

- Lee-Ping

**Comment by jsjyhzy** [comment]
Thank you for your comprehensive explanation, the PR #161 is submitted, and I thought this would be a little bit more elegant.

**Comment by leeping** [comment]
Thank you. :) I merged your changes. Thanks for your patience.
