### ISSUE TITLE
Hessian update after rejected step

### ISSUE THREAD

**Issue by annulen** [leeping/geomeTRIC#181]
As far as I understand code in `optimize.py`, when step is rejected Hessian is not updated with gradients of the last (bad) point — there is a `return` statement after history rollback at https://github.com/leeping/geomeTRIC/blob/master/geometric/optimize.py#L688.

However, we computed one more point of PES, and while we take a step back it seems to me like a loss of important information if we completely throw away computed energy and gradients. Instead of only decreasing trust radius we could make a step into a better direction.

Disclaimer: I have only a vague understanding of how Hessian updates work. I guess a different algorithm may be required to make a proper update after misstep.

**Comment by annulen** [comment]
It would also improve a situation when `tmin` is reached. Currently `Not rejecting step - trust below tmin` is triggered as we have no leeway to decrease trust radius, but with updated hessian we could proceed with rejection and try a  new step that will be different.

**Comment by leeping** [comment]
I think the main problem is that a bad step is often so bad, that one has no guarantee that it will improve the approximate Hessian.  The Hessian updating methods always involve a Taylor series expansion of the PES around the previous step, and assume that we are in a locally quadratic region. However, a bad step that is large (say, dmax > 2e-1) could cause atoms to "clash", which is far outside of the quadratic region. Therefore it is hard to decide whether a bad step should be included in the Hessian update or not.

The other consideration is the Hessian update is for the "new" position, so that the optimization step is rejected and one updates the Hessian using the rejected step, formally that is not the approximate Hessian that should be used for the "original" point.  It is possible one could take the rejected step "virtually" and update the Hessian, then take the exact step backward to the original and update the Hessian again.  That may or may not leave the Hessian unchanged.

In any case, if updating the Hessian for rejected steps actually improves the optimization performance, it could be tested by hacking the code and seeing if it actually performs differently.  I still suspect the issue lies with energy / gradient inconsistency, however.

**Comment by annulen** [comment]
Now I think the right way to deal with it would be to replace step rejection with a "step back" feature (for steps that are considered small enough and close enough by energy). "Step back" should attempt to interpolate PES between good and bad points using all available data and make a proper step to the point in-between where energy is expected to be at minimum. No clever tricks to update Hessian then. However, it may happen that new step is too short, in that case step should be rejected the same way as it's done now (or maybe even stop optimization, as that would mean something is really broken)

**Comment by leeping** [comment]
The geometry optimization algorithm in Gaussian uses a quartic polynomial to estimate the lowest energy point between the current energy / gradient calculation and the previous one. A test implementation is [here](https://github.com/leeping/geometric/tree/interpolation). More testing is needed to determine whether this improves performance.
